### ISSUE TITLE
C++ sample code for using mihasher?

### ISSUE THREAD

**Issue by ns-wxin** [norouzi/mih#11]
I understand this is a very old repo and it uses matlab libraries. I wonder where I can find some sample c++ code that directly uses mihasher class to store hashes and then do a query against it.

The comments inside the code wasn't clear how to use mihasher class and I got some error by guessing the usage.

**Comment by norouzi** [comment]
Sorry, I'm not maintaining this code anymore.

**Comment by ns-wxin** [comment]
Thanks for getting back.
