### ISSUE TITLE
create_lsh_codes.m unfefined function 'fvecs_read'

### ISSUE THREAD

**Issue by simongog** [norouzi/mih#4]
Hi there. I tried to use the matlab script described in the README file to generate lsh codes to feed into your benchmark, but I get an error that a function called `fvecs_read` is not available. Can you please check this? 
Do I have to include other matlab code?

```
>> run('create_lsh_codes.m')
Computing the data mean for the sift_1M dataset... 
Undefined function or variable 'fvecs_read'.

Error in create_lsh_codes (line 60)
    trdata = fvecs_read([datahome, '/ANN_SIFT1M/sift/sift_learn.fvecs']);
```

Thanks you.

**Comment by norouzi** [comment]
Hello, Yes, please download matlab files from http://corpus-texmex.irisa.fr/, and store them in the matlab directory.

**Comment by simongog** [comment]
Thanks @norouzi ! Maybe downloading these scripts should be automized in the RUN.sh script?

**Comment by norouzi** [comment]
I assumed that downloading the matlab files associated with the inria dataset should be part of downloading the data, and after taking a closer look I think the matlab files for inria were supposed to be stored under `data/inria/matlab`.

Unless, we automate the data download, we should not automate download of the matlab files, I think. But feel free to initiate any pull request that you think will be helpful for the user.
